### ISSUE TITLE
Notifications check interval

### ISSUE THREAD

**Issue by marcosilva85** [indywidualny/FaceSlim#119]
Hi,
the new notifications feature is really a nice addition, now we can get notified about chat messages too!
However, it would be nice to have more "check interval" options, like each minute or each 2 minutes.
What you think? Thanks.

**Comment by indywidualny** [comment]
Sure, I will add 2 minutes but you should know that it may impact your
battery life and data usage.

wt., 2.02.2016 o 20:37 użytkownik marcosilva85 <notifications@github.com>
napisał:

**Comment by marcosilva85** [comment]
True, I'm aware of the battery life impact, personally I would use 2 minutes, but for some people it still it would be nice to have 1 minute option (e.g. those with Galaxy Note's / Edge / Plus where battery life is not that of an issue).

**Comment by indywidualny** [comment]
Well. It's just a matter of adding new values to an array so I will do it
for sure soon :)

I'm not sure about 1 minute. I have to check and sum up all the timeouts
because the checkers try up to 3 times when there are any problems getting
the data. Each trial has a 10s timeout but message checker tries two
different sources each time when something is wrong.

In extremely rare cases (terrible network connection and bad luck) checking
time may be close to 60s. So it may be not a good idea to run next checker
right away or even simultaneously.

We don't want problems. But maybe I'm wrong. I will look through the code
:)

wt., 2.02.2016, 20:52 marcosilva85 użytkownik <notifications@github.com>
napisał:

**Comment by marcosilva85** [comment]
In that case, 2 minutes would be a problem-free solution for right now. Well better than 5min at least ;)
