### ISSUE TITLE
can't zoom picture

### ISSUE THREAD

**Issue by NeroBurner** [indywidualny/FaceSlim#130]
In the official app I can double-tap or use two fingers to zoom into the picture. In faceslim two finger zoom does nothing and double-tap just reloads the picture or loads the next picture if available

**Comment by indywidualny** [comment]
Yes. It's the expected behaviour. Please remember it's just a kind of wrapper and if you cannot do something with Facebook mobile website you cannot do it with this app too.

To be able to resize pictures just open a full size picture (link below a picture). This way you are able not only to resize them but also to save them.

**Comment by NeroBurner** [comment]
Thanks for the awesome app and for your fast answer, works perfectly
