### ISSUE TITLE
Facebook to remove messages tab from m.facebok.com

### ISSUE THREAD

**Issue by juk47ht** [indywidualny/FaceSlim#155]
Just saw this on reddit: https://www.reddit.com/r/Android/comments/4f5pcg/psa_facebook_is_planning_on_removing/

A few users reported that when they click on messages tab on m.facebook.com they were greeted with a message suggesting to download the official messenger app from play store. As of yet I haven't faced with a problem on my FaceSlim app. 

Just wanted to give you heads up.

**Comment by indywidualny** [comment]
I'm using Reddit too and noticed this unfortunate announcement. Well, for
now I prevented the crash. If they are really planning to disable this
feature we are screwed. Let's wait and we will see. I'm not sure there will
be any way to use messages without Messenger but if there is I will make it
happen somehow. Personally I hate Facebook so I'm not gonna surrender and
let them force people to use their battery draining apps :D

niedz., 17.04.2016, 23:04 użytkownik juk47ht <notifications@github.com>
napisał:

**Comment by Imxset21** [comment]
From that thread, [https://www.reddit.com/r/Android/comments/4f5pcg/psa_facebook_is_planning_on_removing/d26fm72](the Swipe for Facebook developer has gotten around this by loading messenger.com directly into the app). Perhaps this could be the way forward?

**Comment by indywidualny** [comment]
Swipe for Facebook dev is a really nice guy :D Ok, it's working for now so maybe they decided to postpone it.

**Comment by brownianmotion** [comment]
Not postponed - some users are already seeing this (at least me). 
![Screenshot of Messenger page in FaceSlim](https://cloud.githubusercontent.com/assets/2409292/14907215/cdfe789e-0e08-11e6-9462-4414d13c6f7f.png)

So far, I can work around this by creating a shortcut in my browser to https://www.facebook.com/messages/ (not m.facebook) and then selecting "open in FaceSlim App" from the browser. This pulls up the desktop FB messages site, which still seems to work for me so far...

**Comment by hyp0r** [comment]
Since yesterday no close button anymore and it's not possible to navigate to the messages from anywhere within the app. Galaxy S7.

I appreciate your work, please keep it going, thank you! :)

![picsart_04-30-10 13 58](https://cloud.githubusercontent.com/assets/18749265/14934800/0a3dbcc0-0ebd-11e6-83f1-0d803f8468b0.jpg)

**Comment by indywidualny** [comment]
Ok, so a workaround is needed. I can change a drawer shortcut for messages. I know that messages work with the full website. I also heard about messenger.com allowing to use chat at mobile device. I can at least point drawer item to one of those sites (which one?) to make it work but it's not the same...

**Comment by hyp0r** [comment]
Well, m.facebook.com and mbasic.facebook.com seem to work with the Firefox app - just not with Face Slim. Is it possible to adjust the user agent (http://chrispederick.com/work/user-agent-switcher/) maybe? If not, Id prefer the usability option (messenger.com).

On 30.04.2016 13:43, Krzysztof Grabowski wrote:

Ok, so a workaround is needed. I can change a drawer shortcut for messages. I know that messages work with the full website. I also heard about messenger.com allowing to use chat at mobile device. I can at least point drawer item to one of those sites (which one?) to make it work but it's not the same...

**Comment by indywidualny** [comment]
It's actually ready. I will publish it today. If someone is going to build it and check is everything ok it would be awesome.

**Comment by hyp0r** [comment]
The messenger.com integration works flawlessly for me (Galaxy S7) now,
after an additional login. Thank you very much!

**Comment by Dostoi** [comment]
It's not resolved for me and a friend of mine.
With the last version and the default user agent (blank setting)

**Comment by indywidualny** [comment]
Blank setting just disables the workaround. It's device's default. You need
the value from here:
https://github.com/indywidualny/FaceSlim/releases/tag/v2.8.0

śr., 20.07.2016, 20:51 użytkownik Dostoi <notifications@github.com> napisał:

**Comment by Dostoi** [comment]
Thanks, it works fine now ! :)

**Comment by rignaneseleo** [comment]
@indywidualny in my app (SlimSocial for Facebook) if I use 
`Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.1.0.4633 Mobile Safari/537.10+`
when I click on an external link, the method **onPageStarted** is called many times with urls from domains like **l.facebook.com** and **lm.facebook.com** and after some seconds, it goes to a white page. 
Did you have the same issue on FaceSlim?
If I remove the custom user agent, I haven't any issue.

Thank you so much.

**Comment by indywidualny** [comment]
I assume you didn't allow for all Facebook domains
in shouldOverrideUrlLoading. It's stuck after a few redirections. Facebook
likes to redirect a lot between their subdomains according to your
connection type. Maybe there is an element which cannot be loaded from one
of the domains and the whole thing gets messed up.

wt., 22.11.2016, 22:13 użytkownik Leonardo <notifications@github.com>
napisał:

@indywidualny <https://github.com/indywidualny> in my app (SlimSocial for
Facebook) if I use
Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko)
Version/10.1.0.4633 Mobile Safari/537.10+
when I click on an external link, the method *onPageStarted* is called many
times with urls from domains like *l.facebook.com <http://l.facebook.com>*
and *lm.facebook.com <http://lm.facebook.com>* and after some seconds, it
goes to a white page.
Did you have the same issue on FaceSlim?
If I remove the custom user agent, I haven't any issue.

Thank you so much.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/indywidualny/FaceSlim/issues/155#issuecomment-262367152>,
or mute the thread
