### ISSUE TITLE
Can't connect on first install

### ISSUE THREAD

**Issue by Dostoi** [indywidualny/FaceSlim#181]
The app isn't usable with the last f-droid version

![smssecure-2016-06-15-105715](https://cloud.githubusercontent.com/assets/7694864/16074020/e62a600e-32e8-11e6-8abe-79f20643bde0.jpeg)

If you tap on the "co", red text spawn on the left of the screen but there isn't any place to write your username and password

**Comment by indywidualny** [comment]
Try to play with user agent. Perhaps the predefined one causes this.

śr., 15.06.2016, 11:05 użytkownik Dostoi <notifications@github.com> napisał:

**Comment by Dostoi** [comment]
It's not happening to me but to a friend of mine who isn't tech savvy, so I can't change the user agent

**Comment by GarciaPL** [comment]
I also would like to confirm that yesterday I installed FaceSlim on Samsung Galaxy S3 and the issue is the same. Is it matter of WebKit ?

**Comment by indywidualny** [comment]
The problem is an user agent. It needs to be removed (set to empty).
Apparently the predefined value is not good for all the devices. You need
to set your own UA string or leave it empty to use UA of the device
(messages will not work).

czw., 16.06.2016, 13:46 użytkownik Lukasz Ciesluk <notifications@github.com>
napisał:

**Comment by GarciaPL** [comment]
Thanks for quick reply. I will try as you wrote today in the evening and I will let you know.

**Comment by GarciaPL** [comment]
I confirm. I removed UA and now it works as expected. Thanks a million.

**Comment by indywidualny** [comment]
No problem. I had to choose a default user agent to fix messages.
Unfortunately as I told it doesn't work for all the devices. It works for
most of them but not all. But it's better to enable messages for most of
people and break the app for only the a few because the solution is trivial.

czw., 16.06.2016, 20:04 użytkownik Lukasz Ciesluk <notifications@github.com>
napisał:

**Comment by GarciaPL** [comment]
You can put additional logic in Face Slim which might check abnormal displaying of just first login page and then remove or set other UA to get satisfy login page. Nevertheless thanks once again!

**Comment by indywidualny** [comment]
Use UA from 2.7. Update to 2.7 as well. Fixed :)
