### ISSUE TITLE
Menu Button Doesn't Work on Android 4

### ISSUE THREAD

**Issue by landry314** [indywidualny/FaceSlim#210]
I am running the newest version of FaceSlim on Android 4.4.4 and the menu button does nothing. I had no idea that this program even had a menu until today when I found it accidentally by a left side swipe. I am thrilled to find access to all these amazing features but I wish I had found them earlier.

Can you please link the menu to the menu button for people on Android 4? Or wait, there is not a menu icon either so how does anyone find this hidden menu? I'm confused.

**Comment by landry314** [comment]
Maybe it is not Android 4 but rather just that I have an old phone with a menu button and I have been forgotten... New Androids don't have this button. But without a menu icon, how does anyone know there is a menu before finding it by accident?

**Comment by indywidualny** [comment]
![screenshot_20161008-184536](https://cloud.githubusercontent.com/assets/9354672/19214592/b7f00d02-8d87-11e6-9dba-48568a05b6f3.png)

First run of the app. I thought it's well explained...

Anyway, I cannot link menu button with the hardware button of the device because this feature is no longer supported. Every new app (for example built for Nougat but supporting older devices) cannot use hardware menu buttons. It's only available for legacy apps, targeted for old devices. More: http://android-developers.blogspot.com/2012/01/say-goodbye-to-menu-button.html

**Comment by landry314** [comment]
ok, i see your point, but, then i suggest an action overflow button as well as the swipe menu...

i guess i missed that tutorial at first launch. i tried out your app a while ago then settled on tinfoil for facebook but only recently when messages stopped working did i come back to faceslim by which time the menu was already a distant memory.

maybe new devices have an action overflow button which works. i will see when i get a new phone soon.

**Comment by creativetrendsapps** [comment]
@landry314 , the overflow menu wouldn't open the navigation drawer as it's not intended to do so. Swiping the navigation drawer out is the proper pattern in Android when there is no drawer indicator.
