### ISSUE TITLE
add dummy font size preference

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#33]
People will be looking for a font size preference. Make one and inside it just say that there is no way to control font size (which I guess is the case.)

**Comment by jidanni** [comment]
Real Facebook Lite allows one to pick among three sizes.

**Comment by indywidualny** [comment]
I can actually change the size but after the page is loaded. I can inject my own css.

Although I'm not planning to do it because it will look bad (switching will take a second every time). 

Adding preference field saying there is no way to control font is IMHO unnecessary and I can write it in a Readme instead.

**Comment by kamathln** [comment]
Not css, but no API to directly change the zoom or DPI or something?

**Comment by jidanni** [comment]
I'm using Face Slim with a magnifying glass, just letting your know. VITA Double II phone.

**Comment by indywidualny** [comment]
I will think about making an option to make fonts bigger but I'm not sure
it's possible for a WebView. I don't want to enable zoom but it may be
necessary. Zoom can break the UI.

śr., 16 wrz 2015, 02:57 Dan Jacobson użytkownik <notifications@github.com>
napisał:
