### ISSUE TITLE
Allow moving to SD card

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#40]
Are you sure notifications won't work if this app is on the SD card? They work fine for real Facebook Lite.
This app my be small but its cache grows with no trim mechanism.

**Comment by indywidualny** [comment]
The cache is auto cleaned. It grows but it shouldn't take more than 20 MB. It's not a huge space usage especially for all the  modern devices. IMHO it's acceptable. 

It have to be installed in internal memory because the notification service will not start at boot. 

http://developer.android.com/guide/topics/data/install-location.html#ShouldNot

"The system delivers the ACTION_BOOT_COMPLETED broadcast before the external storage is mounted to the device. If your application is installed on the external storage, it can never receive this broadcast."

**Comment by jidanni** [comment]
OK mention the auto clean facts somewhere in the menus.
I don't know why com.facebook.lite's notifications still seem to work fine even when their app is kept on the SDcard.

**Comment by indywidualny** [comment]
I mean the cache is managed by the system. The size was never bigger than 20 MB at my device so I suppose it's auto cleaned.

Original Facebook Lite uses Google Cloud Messaging (push notifications) and that's the difference which makes their app better for notifications. Because of that it can also be installed in external memory (I suppose that's the reason).

**Comment by jidanni** [comment]
OK. Closing.
