### ISSUE TITLE
Maybe say on "Terminate" that it won't log you out, or just call it exit (app)

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#41]
Maybe say on "Terminate" that it won't log you out. Else it is too scary to press.

Usually app have an "exit", not a "terminate". So one gets worried.

I suppose if it were called exit then we would have a 80% confidence that it wouldn't log us out instead of the current 70% of "terminate".

Maybe call it "exit app". But probably "exit" is best.

**Comment by indywidualny** [comment]
Thanks. I will change it :)

czw., 17 wrz 2015, 06:24 Dan Jacobson użytkownik <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
On the other hand - all the translations have to be changed too. So maybe it's not a good idea.

However "Terminate" is the perfect word for this option. It's exactly the behaviour Android hates (it manages processes on its own). Actually it shouldn't be there. The same, natural behaviour is after leaving the app by clicking a "back" button. The system will terminate the process when memory is needed for new applications. Otherwise there is no need to close the background process - it's battery efficient. It's better for your battery to resume the app from background instead of loading all the resources again :)
