### ISSUE TITLE
Filename

### ISSUE THREAD

**Issue by juzman** [indywidualny/FaceSlim#58]
Hey,

Not so much an "issue" but I have been following the naming convention that has been going on. I downloaded the APK from F-Droid, and noticed the file name is "org.indywidualni.fblite" to keep is unified, you should also change this to "org.indywidualni.fslim".

**Comment by indywidualny** [comment]
It's this way because of a package name. I cannot actually change it because it would make this app seen as a different one. To allow updates from old versions it have to be the same as before. To change a package name it would be also needed to publish the app again at F-Droid. The name of an app is just a string which can be changed anytime. A package name is for a lifetime.

**Comment by juzman** [comment]
Ah right. Understand. :-)
