### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by juzman** [indywidualny/FaceSlim#80]
Great update to v2.0.0! Loving the black theme!

Regarding "turn off images", I noticed it removes the images for the notifications / messages e.t.c. on the action bar(?) Up top.

Think people may file bug reports for it, so got in first. I know it is due to the wrapper, but can you explicitly allow certain images?

**Comment by indywidualny** [comment]
The only accurate way to ignore images is to disable loading them globally. 

I could just hide most of them in order to allow certain images but it wouldn't save data transfer at all.

**Comment by juzman** [comment]
That makes sense. I'm not too worried, most mobile plans here are 4-6GB per
month. Just thought I would make a "bug" report. :p

**Comment by timofonic** [comment]
Aren't there a way to modify the site by using a Greasemonkey-like engine? You're probably using Android 's WebView, so that may be difficult to do. 

This way, you could modify images by local SVG ones, you could transfer relevant data and forget about UI ones too. 

But this could make your app a lot more complex to develop and maintain too...

**Comment by indywidualny** [comment]
You are right. I'm using a WebView. It's not possible to add any complicated modifications to it because a WebView just cannot be modified so deeply. A WebView is now at Google Play and gets constantly updated so even if there was a way to do so, something would eventually broke after an update. 

However the idea is nice :)

**Comment by kamathln** [comment]
There are multiple use cases why FaceSlim is used, and not all might be true at the same time. For example, I use FaceSlim to limit my bandwidth, but I can afford a bit more processing and RAM usage because my phone is powerful. For someone else, the opposite might be the case. 

Regarding this issue, I don't mind it adding an internal proxy program to filter out what I don't need. 
This also applies to the "new tab" Issue . I don't mind the app getting a little heavier, once I enable the features.
